### PR TITLE
Add signup page

### PR DESCRIPTION
**Pull request by theharq**

### CODE REVIEW

**Comment by tadp** [comment]
fyi I checked on my iphone and had issues clicking the hamburger on the upper right. Also the footer isn't on the bottom.

**Comment by tadp** [comment]
Can we add a flash error when someone tries to register as an existing user?

**Comment by theharq** [comment]
PR updated.

plexmate 2016-07-29 00-15-55

Final styles TBD.

**Comment by tadp** [comment]
Looks great! :+1:

**Pull request merged**
